server:
  port: 8082
spring:
  application:
    name: activityservice
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
  data:
    mongodb:
      uri: mongodb://localhost:27017/fitness_activity
      database: fitness_activity
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: false
    non-secure-port: ${server.port}
    instance-id: localhost:${spring.application.name}:${server.port}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  cloud:
    client:
      hostname: localhost

rabbitmq:
  exchange:
    name: fitness.exchange
  queue:
    name: activity.queue
  routing:
    key: activity.tracking