server:
  port: 8081

spring:
  application:
    name: userservice
  datasource:
    url: jdbc:postgresql://localhost:5432/fitness_user_db
    username: ${username}
    password: ${password}
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  cloud:
    client:
      hostname: localhost

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: false
    non-secure-port: ${server.port}
    instance-id: localhost:${spring.application.name}:${server.port}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/